version: '3.9'

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-stat:
    image: insready/redis-stat
    restart: always
    ports:
      - 8080:63790
    command:
      - --server 
      - redis