services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  redis-stat:
    image: insready/redis-stat
    restart: always
    ports:
      - 8080:63790
    command:
      - --server 
      - redis

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - 5555:5555
    depends_on:
      - redis